# Generated by Django 5.1.2 on 2024-10-26 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Config',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=300, verbose_name='URL')),
                ('typeauth', models.CharField(max_length=100, verbose_name='Type Auth')),
            ],
        ),
    ]
