# Generated by Django 5.1.2 on 2024-10-26 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='config',
            name='Nome',
            field=models.CharField(default='teste', max_length=100, verbose_name='Nome Integração'),
            preserve_default=False,
        ),
    ]
